package cg.rcksoft.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;

/**
 * Entity mapped to table NOTE.
 */
public class Note implements Parcelable {

    public static final Creator<Note> CREATOR = new Creator<Note>() {
        @Override
        public Note createFromParcel(Parcel in) {
            return new Note(in);
        }

        @Override
        public Note[] newArray(int size) {
            return new Note[size];
        }
    };
    private Long id;
    private String title;
    private String description;
    private java.util.Date dateEditNote;
    //new properties
    private String flagFavorite;
    private String dateAlarm;
    private String heurAlarm;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String title, String description, Date dateEditNote, String flagFavorite, String dateAlarm, String heurAlarm) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.dateEditNote = dateEditNote;
        this.flagFavorite = flagFavorite;
        this.dateAlarm = dateAlarm;
        this.heurAlarm = heurAlarm;
    }

    protected Note(Parcel in) {
        if (in.readByte() == 0) {
            id = null;
        } else {
            id = in.readLong();
        }
        title = in.readString();
        description = in.readString();
        flagFavorite = in.readString();
        dateAlarm = in.readString();
        heurAlarm = in.readString();
    }

    /**
     * get new instance
     */
    public static void newInstance(){
        new Note();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public java.util.Date getDateEditNote() {
        return dateEditNote;
    }

    public void setDateEditNote(java.util.Date dateEditNote) {
        this.dateEditNote = dateEditNote;
    }

    public String getFlagFavorite() {
        return flagFavorite;
    }

    public void setFlagFavorite(String flagFavorite) {
        this.flagFavorite = flagFavorite;
    }

    public String getDateAlarm() {
        return dateAlarm;
    }

    public void setDateAlarm(String dateAlarm) {
        this.dateAlarm = dateAlarm;
    }

    public String getHeurAlarm() {
        return heurAlarm;
    }

    public void setHeurAlarm(String heurAlarm) {
        this.heurAlarm = heurAlarm;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        if (id == null) {
            dest.writeByte((byte) 0);
        } else {
            dest.writeByte((byte) 1);
            dest.writeLong(id);
        }
        dest.writeString(title);
        dest.writeString(description);
        dest.writeString(flagFavorite);
        dest.writeString(dateAlarm);
        dest.writeString(heurAlarm);
    }
}
